[versions]
agp = "8.2.0"
kotlin = "1.9.21"
compose-plugin = "1.5.11"
navigation-compose = "2.7.5"
kt-lint-gradle = "11.6.1"

compile-sdk = "34"
min-sdk = "24"
launchpad-compose = "0.0.1"

[libraries]
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kt-lint-gradle = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "kt-lint-gradle" }
